### ISSUE TITLE
Can not calculate hue under 0 over 360

### ISSUE THREAD

**Issue by bangseongbeom** [postcss/postcss-color-function#13]
Can not calculate hue under 0 over 360.
[The CSS color draft](http://drafts.csswg.org/css-color/#funcdef-hsl) says:

> The angle 0deg represents red (as does 360deg, 720deg, etc.)

In this sentence we can infer that numbers under 0 over 360 are allowed.

Input:

``` css
.a {
    color: color(red hue(-120));
    color: color(red hue(0));
    color: color(red hue(+120));

    color: color(blue hue(-120));
    color: color(blue hue(0));
    color: color(blue hue(+120));
}
```

---

Expected:

``` css
.a {
    color: rgb(0, 0, 255); /* Green */
    color: rgb(255, 0, 0);
    color: rgb(0, 255, 0);

    color: rgb(0, 255, 0);
    color: rgb(255, 0, 0);
    color: rgb(0, 0, 255); /* Blue */
}
```

Real:

``` css
.a {
    color: rgb(255, 0, 0); /* Expected green but red */
    color: rgb(255, 0, 0);
    color: rgb(0, 255, 0);

    color: rgb(0, 255, 0);
    color: rgb(255, 0, 0);
    color: rgb(255, 0, 0); /* Expected blue but red */
}
```

**Comment by kinday** [comment]
Hey, @bangseongbeom, my PR should fix this issue, but pay attention to your syntax:

``` css
.absolute-hue {
  color: color(hsl(120, 50%, 50%) hue(-120)); /* results in hsl(240, 50%, 50%) */
}

.relative-hue {
  color: color(hsl(120, 50%, 50%) hue(- 120)); /* results in hsl(0, 50%, 50%) */
}
```

Or as specs say:

> Note: While scaling can be specified without any spaces, like `lightness(*150%)`, adding/subtracting must be done with spaces after the +/-, or else the +/- will be interpreted as part of the number by the CSS parser.
