### ISSUE TITLE
Support color(rgb(36, 72, 99), a(90%))

### ISSUE THREAD

**Issue by onlywei** [postcss/postcss-color-function#21]
If I'm using https://github.com/postcss/postcss-simple-vars, and my code looks like:

``` css
$myColor: rgb(36, 72, 99);

.foo {
  color: color($myColor, a(90%));
}
```

And I run my `postcss-simple-vars` processor _before_ this one, shouldn't it transform into:

``` css
.foo {
  color: color(rgb(36, 72, 99), a(90%));
}
```

Any reason why it wouldn't work from here?
