### ISSUE TITLE
Howto combine color() and  css variables

### ISSUE THREAD

**Issue by henryruhs** [postcss/postcss-color-function#25]
Hello,

I'd like to combine **postcss-color-function** and **postcss-css-variables** in a single declaration:

<pre>
:root
{   --color-primary: #f00;
    --color-primary-light: color(var(--color-primary) l(50%));
}
</pre>

This results a fatal error:

<pre>
 Unable to parse color from string "var(--color-primary)"
</pre>

Thank you

**Comment by MoOx** [comment]
This is working with [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties)

``` css
:root
{   --color-primary: #f00;
    --color-primary-light: color(var(--color-primary) l(50%));
}

body
{
  color: var(--color-primary-light);
}
```

Gives

``` css
body
{
  color: rgb(255, 0, 0);
}
```

(No error, even if the color is unchanged. Try with `a(50%)`).

Try by yourself on [cssnext playground](http://cssnext.io/playground/)

---

postcss-css-variables is harmful in too many way, so I won't do anything special for this plugin. It's exlpained in postcss-custom-properties readme
