### ISSUE TITLE
Color adjuster doesn’t work

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-color-function#40]
Input CSS using the blackness adjuster:

```css
body { background-color: color(#000 b(10%)) }
```

Result CSS after using the blackness adjuster:
```css
body { background-color: rgb(230, 0, 0) }
```

That’s a bold red. Here’s an example:

https://codepen.io/jonneal/pen/a8843ad869e1f31d8448d7ab6dc65a18

Is this limited to the version of cssnext on CodePen or is this still a bug?
