### ISSUE TITLE
Wrong output when using the * operator and <percentage>

### ISSUE THREAD

**Issue by nia1048596** [postcss/postcss-color-function#46]
The color hsl(0, 0%, 10%) with lightness multiplied by 5% should be nearly black, but the output seems to be hsl(0, 0%, 10% * **5**) == rgb(128, 128, 128) rather than hsl(0, 0%, 10% * **5%**). If use 0.05 instead the output is correct.

test.css:
```css
.test1 {
    background-color: color(hsl(0, 0%, 10%) lightness(* 5%));
}
.test2 {
    background-color: color(hsl(0, 0%, 10%) lightness(* 0.05));
}
```

postcss.config.js:
```javascript
module.exports = {
    plugins: {
        'postcss-color-function': {},
    },
}
```

Output:
```bash
nia@nia-PC [~/temp/test] $ ./node_modules/.bin/postcss test.css
✔ Finished test.css (17 ms)
.test1 {
    background-color: rgb(128, 128, 128);
}
.test2 {
    background-color: rgb(3, 3, 3);
}
nia@nia-PC [~/temp/test] $
```

The version is 4.0.0
```bash
nia@nia-PC [~/temp/test] $ npm list postcss-color-function
/home/nia/temp/test
└── postcss-color-function@4.0.0
```

Since the [spec](https://drafts.csswg.org/css-color/#modifying-colors) says we should use `<percentage>`, I think this is a bug.
