### ISSUE TITLE
Custom properties not working as function parameter

### ISSUE THREAD

**Issue by robcalcroft** [postcss/postcss-color-function#48]
We have our CSS custom props defined in a JSON file which is imported like:
```javascript
'postcss-cssnext': {
      browsers: ['>.25%', 'IE 8'],
      features: {
        { '--color-primary': red },
      },
    },
```
We can then use that var as normal with no issues
Then trying to use it with the `color()` function:
```css
&:active {
  border-color: color(var(--color-primary) shade(20%));
}
```
And this doesn't work. The resulting color is just black.

Doing:
```css
&:active {
  border-color: color(red shade(20%));
}
```
does work
