### ISSUE TITLE
Support Custom Properties

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-color-function#49]
If a developer wants to use Custom Properties with this plugin, could this plugin lookup the variables for them? Even if it’s just on `:root`?

Currently, [this plugin relies on PostCSS Custom Properties](https://github.com/postcss/postcss-color-function#can-we-use-css-custom-properties-so-we-can-do-colorvar--maincolor-adjuster) to remove `var()` usage, but 1. that’s not very future-leaning, and 2. the new major release of PostCSS Custom Properties preserves `var()` usage by default.

```css
:root {
  --brand: #00bdbd;
  --dark-brand: color(var(--brand) shade(20%));
}
```

becomes

```css
:root {
  --brand: #00bdbd;
  --dark-brand: color(var(--brand) shade(20%));
}
```

Unfortunately, it seems this plugin was never tested against Custom Properties with the `preserve` option enabled.

https://github.com/postcss/postcss-custom-properties/issues/99
https://github.com/postcss/postcss-custom-properties/issues/98
