### ISSUE TITLE
Please add support for fractional percentages

### ISSUE THREAD

**Issue by jwdallas** [postcss/postcss-color-function#57]
Hello, I’m trying to hit a specific rgb result value with my color transformations and finding there’s no support for fractional percentages.

**Input**
```CSS
fire {
  color: color(rgba(29, 29, 31, 1) tint(4%));
}

water {
  color: color(rgba(29, 29, 31, 1) tint(4.3%));
}
```
**Output**
```CSS
fire {
  color: rgb(38, 38, 40);
}

water {
  color: rgb(38, 38, 40);
}
```

Thanks for creating this wonderful polyfill. It’s been awesome to use.
