### ISSUE TITLE
Working wrong with POSTCSS-CUSTOM-PROPERTIES

### ISSUE THREAD

**Issue by elcoach290** [postcss/postcss-color-function#59]
This is my postcss.config.js
```js
module.exports = {
  plugins: [
    require('postcss-easy-import'),
    require('postcss-mixins'),
    require('postcss-nested'),
    require('postcss-custom-properties'),
    require("postcss-color-function"),
      ]
}
```
In the precompiled file y write:
```css
.header{
    background-color: color(var(--lightcolor) a(30%));
}
```
The result is:
```css
.header{
    background-color: rgba(255, 255, 255, 0.3);
    background-color: color(var(--lightcolor) a(30%));
}
```
 The declaration is duplicated, what I did wrong???

the task is:
```js
"scripts": {
    "css": "postcss pcss/style.pcss -o frontend/css/style.css —no-map —verbose"
}
```
what is missing ???

Thanks for your help friends!!

**Comment by Semigradsky** [comment]
What is your result without `postcss-color-function`?

**Comment by elcoach290** [comment]
@Semigradsky thanks for your help, without postcss-color-function the result is:
```css
.header{
  background-color: color(white a(80%));
  padding: 15px 0;
  padding: var(--spacer) 0;
}
```
Now the padding is duplicated, I thinlk the problem is with the postcss-custom-properties package, is there aditional configuration that I need to do??, My current solution is use postcss-color-function without postcss-custom-properties, but I can't use variables as parameters when I use the color function.
