### ISSUE TITLE
Color functions not being processed

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss-color-function#6]
Beginner question. I'm running PostCSS/postcss-color-function via Gulp and tried a reduction to get to the bottom of my issue. I have this task:

``` javascript
var postcss = require("gulp-postcss"); 
var colorFunction = require("postcss-color-function");

gulp.task("css", function(){
    var processors = [
    colorFunction
        ];
    gulp.src("preCSS/styles.css")
    .pipe(postcss(processors))
    .pipe(gulp.dest("output"));
});
```

Given this input:

``` css
.thing {
   color: color(white a(90%));
}
```

I am getting this (same) output:

``` css
.thing {
   color: color(white a(90%));
}
```

Is this due to the way I am configuring?
